import Head from 'next/head'
import Navbar from '../component/navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        HELLO THERE!
      </h1>
      <Navbar />
    </div>
  )
}
